# Generated by Django 4.2.7 on 2025-09-10 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset", models.CharField(max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("CALL", "Call"), ("PUT", "Put")], max_length=4
                    ),
                ),
                ("entry_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "expiration_time",
                    models.IntegerField(help_text="Tempo de expiração em minutos"),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entrada"),
                            ("GALE1", "Gale 1"),
                            ("GALE2", "Gale 2"),
                            ("GALE3", "Gale 3"),
                        ],
                        default="ENTRY",
                        max_length=10,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("WIN", "Vitória"),
                            ("LOSS", "Derrota"),
                            ("DRAW", "Empate"),
                            ("PENDING", "Pendente"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "iq_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "trading_operation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STOPPED", "Parado"),
                            ("RUNNING", "Executando"),
                            ("PAUSED", "Pausado"),
                            ("ERROR", "Erro"),
                        ],
                        default="STOPPED",
                        max_length=10,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(help_text="Estratégia utilizada", max_length=50),
                ),
                ("asset", models.CharField(help_text="Ativo negociado", max_length=20)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("PRACTICE", "Demo"), ("REAL", "Real")],
                        default="PRACTICE",
                        max_length=10,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_operations", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trading_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TradingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="trading.operation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="trading.tradingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trading_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="trading.tradingsession",
            ),
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=20)),
                ("timeframe", models.IntegerField(help_text="Timeframe em segundos")),
                ("open_price", models.DecimalField(decimal_places=8, max_digits=15)),
                ("high_price", models.DecimalField(decimal_places=8, max_digits=15)),
                ("low_price", models.DecimalField(decimal_places=8, max_digits=15)),
                ("close_price", models.DecimalField(decimal_places=8, max_digits=15)),
                (
                    "volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trading_market_data",
                "ordering": ["-timestamp"],
                "unique_together": {("asset", "timeframe", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="AssetCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=20)),
                ("strategy", models.CharField(max_length=50)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gale1_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gale2_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_samples", models.IntegerField(default=0)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_catalogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trading_asset_catalog",
                "ordering": ["-win_rate"],
                "unique_together": {("user", "asset", "strategy")},
            },
        ),
    ]
