# Generated by Django 4.2.7 on 2025-09-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcatalog',
            name='gale3_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
