# Generated by Django 4.2.7 on 2026-05-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_assetcatalog_gale3_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetcatalog",
            options={"ordering": ["-score", "-win_rate"]},
        ),
        migrations.AddField(
            model_name="assetcatalog",
            name="mtf_analysis",
            field=models.JSONField(
                blank=True, default=dict, help_text="Multi-timeframe analysis data"
            ),
        ),
        migrations.AddField(
            model_name="assetcatalog",
            name="payout",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="assetcatalog",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Composite score for ranking",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="assetcatalog",
            name="trend",
            field=models.CharField(
                choices=[("UP", "Alta"), ("DOWN", "Baixa"), ("SIDEWAYS", "Lateral")],
                default="SIDEWAYS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="assetcatalog",
            name="trend_strength",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
