# Generated by Django 4.2.7 on 2026-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trading",
            "0003_alter_assetcatalog_options_assetcatalog_mtf_analysis_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetcatalog",
            name="analyzed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tradingsession",
            name="account_type",
            field=models.CharField(
                choices=[("PRACTICE", "Demo"), ("REAL", "Real")],
                default="REAL",
                max_length=10,
            ),
        ),
    ]
