# Generated by Django 4.2.7 on 2025-09-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradingconfiguration",
            old_name="moving_averages_candles",
            new_name="velas_medias",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="analyze_moving_averages",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="entry_value",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="martingale_factor",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="martingale_levels",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="operation_type",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="soros_levels",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="use_martingale",
        ),
        migrations.RemoveField(
            model_name="tradingconfiguration",
            name="use_soros",
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="analise_medias",
            field=models.BooleanField(
                default=False, help_text="Análise de médias (N=False, S=True)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="default_strategy",
            field=models.CharField(
                choices=[
                    ("mhi", "MHI"),
                    ("torres_gemeas", "Torres Gêmeas"),
                    ("mhi_m5", "MHI M5"),
                ],
                default="mhi",
                help_text="Estratégia padrão",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="martingale_fator",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Fator multiplicador do Martingale",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="martingale_niveis",
            field=models.IntegerField(default=1, help_text="Níveis do Martingale"),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="martingale_usar",
            field=models.BooleanField(
                default=True, help_text="Usar Martingale (S=True, N=False)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="soros_niveis",
            field=models.IntegerField(default=1, help_text="Níveis do Soros"),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="soros_usar",
            field=models.BooleanField(
                default=True, help_text="Usar Soros (S=True, N=False)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="tipo",
            field=models.CharField(
                choices=[("automatico", "Automático"), ("manual", "Manual")],
                default="automatico",
                help_text="Tipo de operação",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="tipo_par",
            field=models.CharField(
                choices=[
                    ("automatico", "Automático (Todos os Pares)"),
                    ("manual", "Manual"),
                ],
                default="automatico",
                help_text="Tipo de par para trading",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="valor_entrada",
            field=models.DecimalField(
                decimal_places=2,
                default=3.0,
                help_text="Valor de entrada",
                max_digits=10,
            ),
        ),
        migrations.AlterModelTable(
            name="tradingconfiguration",
            table="user_trading_configuration",
        ),
    ]
