# Generated by Django 4.2.7 on 2025-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfiguration",
            name="torres_break_buffer_pct",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                help_text="Buffer extra para confirmar rompimento em %",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="torres_event_cooldown_sec",
            field=models.IntegerField(
                default=45, help_text="Cooldown entre sinais event-driven (s)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="torres_event_driven",
            field=models.BooleanField(
                default=False, help_text="Acionar por rompimento (sem gate de minuto)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="torres_lookback",
            field=models.IntegerField(
                default=60, help_text="Número de velas para detectar A-B-C"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="torres_timeframe",
            field=models.IntegerField(
                default=60, help_text="Timeframe em segundos (padrão M1=60)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="torres_tolerancia_pct",
            field=models.DecimalField(
                decimal_places=3,
                default=0.05,
                help_text="Tolerância de similaridade das torres em %",
                max_digits=6,
            ),
        ),
    ]
