# Generated by Django 4.2.7 on 2025-09-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_tradingconfiguration_torres_break_buffer_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfiguration",
            name="bb_period",
            field=models.IntegerField(
                default=20, help_text="Período das Bollinger Bands (padrão 20)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="bb_std_dev",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Desvio padrão das Bollinger Bands (padrão 2.0)",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="bb_timeframe",
            field=models.IntegerField(
                default=60, help_text="Timeframe em segundos para BB (padrão M1=60)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="bb_touch_threshold",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0001,
                help_text="Threshold para detectar toque na banda (padrão 0.0001)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="ma_fast_period",
            field=models.IntegerField(
                default=9, help_text="Período da média móvel rápida (padrão 9)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="ma_slow_period",
            field=models.IntegerField(
                default=21, help_text="Período da média móvel lenta (padrão 21)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="ma_timeframe",
            field=models.IntegerField(
                default=60, help_text="Timeframe em segundos para MA (padrão M1=60)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="rsi_overbought",
            field=models.IntegerField(
                default=70, help_text="Nível de sobrecompra do RSI (padrão 70)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="rsi_oversold",
            field=models.IntegerField(
                default=30, help_text="Nível de sobrevenda do RSI (padrão 30)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="rsi_period",
            field=models.IntegerField(
                default=14, help_text="Período do RSI (padrão 14)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="rsi_timeframe",
            field=models.IntegerField(
                default=60, help_text="Timeframe em segundos para RSI (padrão M1=60)"
            ),
        ),
        migrations.AlterField(
            model_name="tradingconfiguration",
            name="default_strategy",
            field=models.CharField(
                choices=[
                    ("mhi", "MHI"),
                    ("torres_gemeas", "Torres Gêmeas"),
                    ("mhi_m5", "MHI M5"),
                    ("rsi", "RSI"),
                    ("moving_average", "Moving Average"),
                    ("bollinger_bands", "Bollinger Bands"),
                ],
                default="mhi",
                help_text="Estratégia padrão",
                max_length=20,
            ),
        ),
    ]
