# Generated by Django 4.2.7 on 2025-09-14 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_tradingconfiguration_bb_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfiguration",
            name="cs_body_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                help_text="Threshold para tamanho do corpo",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="cs_doji_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Threshold para detecção de Doji",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="cs_shadow_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Proporção mínima da sombra",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="engulfing_confirmation_candles",
            field=models.IntegerField(
                default=1, help_text="Número de velas para confirmação"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="engulfing_min_body_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=1.2,
                help_text="Proporção mínima do corpo engolidor",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="macd_fast_period",
            field=models.IntegerField(default=12, help_text="Período da EMA rápida"),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="macd_min_histogram",
            field=models.DecimalField(
                decimal_places=8,
                default=1e-05,
                help_text="Threshold mínimo do histograma",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="macd_signal_period",
            field=models.IntegerField(default=9, help_text="Período da linha de sinal"),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="macd_slow_period",
            field=models.IntegerField(default=26, help_text="Período da EMA lenta"),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="macd_timeframe",
            field=models.IntegerField(
                default=60, help_text="Timeframe em segundos (60=M1, 300=M5)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cs_body_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                help_text="Threshold para tamanho do corpo",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cs_doji_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Threshold para detecção de Doji",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cs_shadow_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Proporção mínima da sombra",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="engulfing_confirmation_candles",
            field=models.IntegerField(
                default=1, help_text="Número de velas para confirmação"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="engulfing_min_body_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=1.2,
                help_text="Proporção mínima do corpo engolidor",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="macd_fast_period",
            field=models.IntegerField(default=12, help_text="Período da EMA rápida"),
        ),
        migrations.AddField(
            model_name="user",
            name="macd_min_histogram",
            field=models.DecimalField(
                decimal_places=8,
                default=1e-05,
                help_text="Threshold mínimo do histograma",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="macd_signal_period",
            field=models.IntegerField(default=9, help_text="Período da linha de sinal"),
        ),
        migrations.AddField(
            model_name="user",
            name="macd_slow_period",
            field=models.IntegerField(default=26, help_text="Período da EMA lenta"),
        ),
        migrations.AddField(
            model_name="user",
            name="macd_timeframe",
            field=models.IntegerField(
                default=60, help_text="Timeframe em segundos (60=M1, 300=M5)"
            ),
        ),
        migrations.AlterField(
            model_name="tradingconfiguration",
            name="default_strategy",
            field=models.CharField(
                choices=[
                    ("mhi", "MHI"),
                    ("torres_gemeas", "Torres Gêmeas"),
                    ("mhi_m5", "MHI M5"),
                    ("rsi", "RSI"),
                    ("moving_average", "Moving Average"),
                    ("bollinger_bands", "Bollinger Bands"),
                    ("engulfing", "Engolfo (Engulfing)"),
                    ("candlestick", "Padrões de Candlestick"),
                    ("macd", "MACD"),
                ],
                default="mhi",
                help_text="Estratégia padrão",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Threshold para toque nas bandas",
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
