# Generated by Django 4.2.7 on 2025-09-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_tradingconfiguration_cs_body_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfiguration",
            name="filtros_ativos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de filtros ativos para confirmação de sinais",
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="media_movel_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.15,
                help_text="Threshold para filtro de média móvel",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="rodrigo_risco_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.75,
                help_text="Threshold para filtro Rodrigo Risco",
                max_digits=4,
            ),
        ),
    ]
