# Generated by Django 4.2.7 on 2025-09-15 20:38

from django.db import migrations, models


def update_preferred_account_type(apps, schema_editor):
    """Update existing users to use REAL account type by default"""
    User = apps.get_model('accounts', 'User')
    
    # Update all users that currently have PRACTICE to REAL
    User.objects.filter(preferred_account_type='PRACTICE').update(preferred_account_type='REAL')


def reverse_preferred_account_type(apps, schema_editor):
    """Reverse migration - set back to PRACTICE"""
    User = apps.get_model('accounts', 'User')
    
    # Update all users back to PRACTICE
    User.objects.filter(preferred_account_type='REAL').update(preferred_account_type='PRACTICE')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tradingconfiguration_filtros_ativos_and_more'),
    ]

    operations = [
        # First change the default value in the model
        migrations.AlterField(
            model_name='user',
            name='preferred_account_type',
            field=models.CharField(
                choices=[('PRACTICE', 'Demo'), ('REAL', 'Real')],
                default='REAL',
                help_text='Tipo de conta preferido para trading',
                max_length=10
            ),
        ),
        # Then update existing users
        migrations.RunPython(
            update_preferred_account_type,
            reverse_preferred_account_type
        ),
    ]
