# Generated by Django 4.2.7 on 2026-05-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_update_preferred_account_type_to_real"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfiguration",
            name="asset_blacklist",
            field=models.JSONField(
                blank=True, default=list, help_text="Lista de ativos bloqueados"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="auto_select_asset",
            field=models.BooleanField(
                default=False,
                help_text="Selecionar automaticamente o melhor ativo do catálogo",
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="check_correlation",
            field=models.BooleanField(
                default=True, help_text="Verificar correlação entre ativos"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="daily_loss_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="Limite de perda diária",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="max_consecutive_losses",
            field=models.IntegerField(
                default=3, help_text="Parar após X perdas consecutivas"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="max_correlated_positions",
            field=models.IntegerField(
                default=2, help_text="Máximo de posições em ativos correlacionados"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="min_gale1_rate_filter",
            field=models.DecimalField(
                decimal_places=2,
                default=75.0,
                help_text="Taxa mínima de Gale1 para filtrar ativos (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="min_win_rate_filter",
            field=models.DecimalField(
                decimal_places=2,
                default=60.0,
                help_text="Taxa mínima de acerto para filtrar ativos (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="mtf_timeframes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Timeframes para análise (em segundos)",
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="trading_end_hour",
            field=models.IntegerField(
                default=21, help_text="Hora de fim das operações (UTC)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="trading_start_hour",
            field=models.IntegerField(
                default=9, help_text="Hora de início das operações (UTC)"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="use_multi_timeframe",
            field=models.BooleanField(
                default=True, help_text="Usar análise multi-timeframe para confirmação"
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="use_trading_schedule",
            field=models.BooleanField(
                default=False, help_text="Usar horários de operação recomendados"
            ),
        ),
    ]
