# Generated by Django 4.2.7 on 2026-05-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_tradingconfiguration_asset_blacklist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingconfiguration",
            name="placar_stop_loss",
            field=models.IntegerField(
                default=3,
                help_text="Diferença de erros para Stop Loss (ex: 3 = 0x3, 1x4, 2x5...)",
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="placar_stop_win",
            field=models.IntegerField(
                default=3,
                help_text="Diferença de acertos para Stop Win (ex: 3 = 3x0, 4x1, 5x2...)",
            ),
        ),
        migrations.AddField(
            model_name="tradingconfiguration",
            name="stop_por_placar",
            field=models.BooleanField(
                default=False,
                help_text="Usar stop por placar em vez de valor monetário",
            ),
        ),
    ]
